package traductor.aLexico;
//Estados de nuestro automata
public enum MaquinaEstados {
	EINICIAL,
	ENUMCERO,
	ENUMERO,
	EIDENOPALRES,
	ECOMA,
	EPUNTO,
	EPUNTOYCOMA,
	EDOSPUNTOS,
	EASIGNACION,
	EPARENTESISAPER,
	EPARENTESISCIER,
	ESUMORESOMULODIV,
	EIGUAL,
	EMENOR,
	EMAYOR,
	EMENORIGUAL,
	EMAYORIGUAL,
	EDISTINTO,
	ECORCHETEAPER,
	ECORCHETECIER,
	EPUNTERO;
	
}
